const BREEDS = [
  'LABRADOR RETRIEVER',
  'GERMAN SHEPHERD',
  'GOLDEN RETRIEVER',
  'BULLDOG',
  'BEAGLE',
  'FRENCH BULLDOG',
  'YORKSHIRE TERRIER',
  'POODLE',
  'ROTTWEILER',
  'BOXER',
  'POINTER',
  'SIBERIAN HUSKIE',
  'DACHSHUND'
];

module.exports = BREEDS;
